import { useMemo,useState } from 'react'
import { useLocation } from 'react-router-dom'
import EmployeeLayout from '../components/EmployeeLayout'
import QueueTable from '../components/QueueTable'
import MetricCards from '../components/MetricCards'
import StatusPill from '../../queue/components/StatusPill'
import Modal from '../../../shared/components/Modal'
import Button from '../../../shared/components/Button'
import StatePanel from '../../../shared/components/StatePanel'
import ToastHost from '../../../shared/components/ToastHost'
import { useLanguage } from '../../../shared/hooks/useLanguage'
import { getService,callNext,transitionTicket } from '../../queue/services/queueService'
import { useQueueState } from '../../queue/hooks/useQueue'

export default function EmployeePage(){const loc=useLocation();const mode=loc.pathname.endsWith('/waiting')?'waiting':loc.pathname.endsWith('/current')?'current':'dashboard';const{state,refresh}=useQueueState();const{t}=useLanguage();const[dialog,setDialog]=useState(null);const[toast,setToast]=useState(null);const waiting=useMemo(()=>state.tickets.filter(x=>x.status==='WAITING').sort((a,b)=>a.createdAt-b.createdAt),[state]);const current=state.tickets.find(x=>x.status==='CALLED'||x.status==='SERVING')||null;const serviceName=id=>{const s=getService(id);return s?t(`serviceNames.${s.nameKey}`):id};const next=()=>{try{callNext();setToast({message:t('toast.updated')});refresh()}catch(e){setToast({type:'error',message:e.message==='EMPTY'?t('errors.empty'):t('errors.busy')})}};const trans=(id,status)=>{try{transitionTicket(id,status);setToast({message:status==='DONE'?t('toast.done'):status==='SERVING'?t('toast.started'):status==='SKIPPED'?t('toast.skipped'):t('toast.cancelled')});setDialog(null);refresh()}catch{setToast({type:'error',message:t('errors.invalidTransition')})}};return <EmployeeLayout><main className="min-w-0 p-4 sm:p-6 lg:p-7 xl:p-8">{mode==='dashboard'?<Dashboard/>:mode==='waiting'?<Waiting/>:<Current/>}</main><ToastHost toast={toast} onClose={()=>setToast(null)}/><Modal open={!!dialog} onClose={()=>setDialog(null)} title={dialog?.action==='skip'?t('employee.skipTitle'):t('employee.cancelTitle')} body={dialog?((dialog.action==='skip'?t('employee.skipBody'):t('employee.cancelBody')).replace('{number}',dialog.ticket.number)):''}><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={()=>setDialog(null)}>{t('common.back')}</Button><Button variant={dialog?.action==='skip'?'secondary':'dangerOutline'} onClick={()=>trans(dialog.ticket.id,dialog.action==='skip'?'SKIPPED':'CANCELLED')}>{dialog?.action==='skip'?t('employee.skipTicket'):t('employee.cancelTicket')}</Button></div></Modal></EmployeeLayout>

function Dashboard(){const title=t('employee.title');return <><Header title={title} right={<div className="flex gap-2"><span className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 font-mono text-[9px] uppercase tracking-[0.12em] text-slate-500">{waiting.length} {t('states.WAITING')}</span><span className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 font-mono text-[9px] uppercase tracking-[0.12em] text-slate-500">{t('employee.serving')} {state.currentServing||'—'}</span></div>}/><div className="grid gap-5 xl:grid-cols-[255px_minmax(0,1fr)]"><CurrentPanel/><QueueSection/></div></>}
function Waiting(){const q=new URLSearchParams(loc.search);const requested=q.get('state');if(requested==='empty')return <><Header title={t('employee.waitingNav')} right={<Button disabled>{t('employee.next')}</Button>}/><StatePanel type="empty" title={t('employee.emptyTitle')} body={t('employee.emptyBody')} actionLabel={t('employee.refresh')} onAction={()=>window.location.reload()}/></>;if(requested==='error')return <><Header title={t('employee.waitingNav')} right={<Button>{t('employee.next')}</Button>}/><StatePanel title={t('employee.errorTitle')} body={t('employee.errorBody')} actionLabel={t('employee.tryAgain')} onAction={()=>location.assign('/employee/waiting')}/></>;return <><Header title={t('employee.waitingNav')} right={<Button disabled={!waiting.length||current}>{t('employee.next')}</Button>}/><MetricCards metrics={[{value:waiting.length,label:t('employee.metricWaiting')},{value:state.currentServing||'—',label:t('employee.metricServing')},{value:state.doneToday,label:t('employee.metricDone')},{value:'~14m',label:t('employee.metricAvg')}]}/><QueueSection/><div className="mt-1 rounded border border-dashed border-slate-300 bg-white px-3 py-2 text-[9px] text-slate-500"><span className="me-1 font-mono">NOTE</span>{t('employee.dashboardRule')}</div></>}
function Current(){return <><Header title={t('employee.currentNav')}/><div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.1fr)_345px]"><section className="min-h-[365px] rounded-xl border-2 border-navy-950 bg-white p-7 text-center shadow-sm"><TicketHero ticket={current}/></section><div className="grid gap-4"><ActionCard/><UpNext/></div></div></>}
function Header({title,right}){return <div className="mb-7 flex items-start justify-between gap-4"><h1 className="text-[22px] font-extrabold tracking-[-0.04em]">{title}</h1>{right}</div>}
function CurrentPanel(){return <section><div className="mb-2 font-mono text-[8px] font-bold uppercase tracking-[0.18em] text-slate-400">{t('employee.current')}</div><div className="rounded-xl border-2 border-navy-950 bg-white p-5 text-center shadow-sm"><TicketHero ticket={current} compact/></div><Button className="mt-2.5 w-full" disabled={!waiting.length||current} onClick={next}>{t('employee.next')}</Button></section>}
function TicketHero({ticket,compact=false}){return <>{<div className={`${compact?'text-4xl':'text-6xl'} font-mono font-black tracking-[-0.09em] ${ticket?.status==='SERVING'?'text-teal-600':'text-brand-600'}`}>{ticket?.number||'—'}</div>}{ticket&&<><div className="mt-2 text-sm text-slate-500">{serviceName(ticket.serviceId)}</div><div className="mt-2"><StatusPill status={ticket.status} t={t}/></div>{!compact&&<div className="mt-7 border-t border-dotted border-slate-300 pt-4 text-start">{ticket.calledAt&&<DataLine label={t('employee.calledAt')} value={ticket.calledAt}/>} {ticket.startedAt&&<DataLine label={t('employee.startedAt')} value={ticket.startedAt}/>}<DataLine label={t('employee.waited')} value={`${ticket.waited||18} min`}/></div>}{compact&&<ActionButtons ticket={ticket}/>}</>}</>}
function ActionButtons({ticket}){if(!ticket)return null;if(ticket.status==='CALLED')return <div className="mt-3 grid gap-2"><Button className="w-full" onClick={()=>trans(ticket.id,'SERVING')}>{t('common.start')}</Button><div className="grid grid-cols-2 gap-2"><Button variant="secondary" onClick={()=>setDialog({ticket,action:'skip'})}>{t('common.skip')}</Button><Button variant="dangerOutline" onClick={()=>setDialog({ticket,action:'cancel'})}>! {t('common.cancel')}</Button></div></div>;if(ticket.status==='SERVING')return <Button className="mt-3 w-full" variant="teal" onClick={()=>trans(ticket.id,'DONE')}>{t('common.done')}</Button>;return null}
function ActionCard(){return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-3 font-mono text-[8px] uppercase tracking-[0.16em] text-slate-400">{t('employee.actions')}</div>{current?<ActionButtons ticket={current}/>:<div className="text-sm text-slate-500">{t('employee.emptyTitle')}</div>}<div className="mt-2 rounded border border-dashed border-slate-300 bg-slate-50 px-3 py-2 text-[9px] text-slate-500">{current?.status==='SERVING'?t('employee.servingNote'):t('employee.calledNote')}</div></section>}
function UpNext(){return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-3 font-mono text-[8px] uppercase tracking-[0.16em] text-slate-400">{t('employee.upNext')}</div><div className="grid gap-2">{waiting.slice(0,2).map(ticket=><div key={ticket.id} className="flex min-h-12 items-center justify-between gap-3 rounded-lg border border-slate-200 p-3"><div><strong className="font-mono text-sm">{ticket.number}</strong><div className="text-[9px] text-slate-500">{serviceName(ticket.serviceId)}</div></div><StatusPill status="WAITING" t={t} compact/></div>)}</div></section>}
function QueueSection(){return <section><div className="mb-2 flex items-center justify-between"><div className="font-mono text-[8px] uppercase tracking-[0.18em] text-slate-400">{t('employee.waitingTitle')}</div><span className="font-mono text-[9px] text-slate-400">{waiting.length} {t('employee.tickets')}</span></div><QueueTable waiting={waiting} serviceName={serviceName}/></section>}
function DataLine({label,value}){return <div className="flex min-h-8 items-center justify-between border-b border-dotted border-slate-300 text-xs text-slate-500"><span>{label}</span><strong className="font-mono text-navy-950">{value}</strong></div>}
}