import { LockKeyhole,UserRound,ArrowRight } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Button from '../../../shared/components/Button'
import LanguageToggle from '../../../shared/components/LanguageToggle'
import Logo from '../../../shared/components/Logo'
import { useLanguage } from '../../../shared/hooks/useLanguage'
import { loginEmployee } from '../../queue/services/authService'
export default function LoginPage(){const{t}=useLanguage();const nav=useNavigate();const[name,setName]=useState('');const[password,setPassword]=useState('');const submit=e=>{e.preventDefault();loginEmployee(name||t('employee.account'));nav('/employee')};return <div className="min-h-screen bg-slate-50"><div className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-4 sm:px-6"><Logo/><LanguageToggle/></div><main className="mx-auto grid min-h-[calc(100vh-73px)] max-w-6xl items-center gap-10 px-4 py-8 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="rounded-3xl bg-brand-500 p-8 text-white shadow-sm sm:p-10"><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-brand-100">QueueNow · Employee</div><h1 className="mt-4 text-4xl font-extrabold tracking-[-0.04em]">{t('employee.loginTitle')}</h1><p className="mt-4 max-w-md text-sm leading-6 text-brand-50">{t('employee.loginHint')}</p><div className="mt-8 flex items-center gap-3 rounded-2xl border border-white/20 bg-white/10 p-4"><span className="grid size-10 place-items-center rounded-xl bg-white/15"><UserRound/></span><div><div className="text-xs text-brand-100">{t('employee.signed')}</div><div className="font-semibold">{t('employee.doctor')}</div></div></div></div><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-extrabold text-navy-950">{t('employee.loginTitle')}</h2><form onSubmit={submit} className="mt-7 space-y-5"><label className="block"><span className="text-sm font-semibold text-navy-950">{t('employee.loginName')}</span><div className="relative mt-2"><UserRound className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder={t('employee.loginNamePlaceholder')} className="h-12 w-full rounded-xl border border-slate-300 bg-white ps-10 pe-4 text-sm outline-none focus:border-brand-400 focus:ring-4 focus:ring-brand-50"/></div></label><label className="block"><span className="text-sm font-semibold text-navy-950">{t('employee.loginPassword')}</span><div className="relative mt-2"><LockKeyhole className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={t('employee.loginPasswordPlaceholder')} className="h-12 w-full rounded-xl border border-slate-300 bg-white ps-10 pe-4 text-sm outline-none focus:border-brand-400 focus:ring-4 focus:ring-brand-50"/></div></label><button type="button" className="text-sm text-slate-500 hover:text-brand-600">{t('employee.forgot')}</button><Button type="submit" className="w-full">{t('employee.login')}<ArrowRight className="size-4"/></Button></form></section></main></div>}
